export const cities = [
  'Aberdeen',
  'Armagh',
  'Bangor',
  'Bath',
  'Belfast',
  'Birmingham',
  'Bradford',
  'Brighton & Hove',
  'Bristol',
  'Cambridge',
  'Canterbury',
  'Cardiff',
  'Carlisle',
  'Chelmsford',
  'Chester',
  'Chichester',
  'Colchester',
  'Coventry',
  'Derby',
  'Doncaster',
  'Dunfermline',
  'Dundee',
  'Durham',
  'Edinburgh',
  'Ely',
  'Exeter',
  'Glasgow',
  'Gloucester',
  'Hereford',
  'Inverness',
  'Kingston-upon-Hull',
  'Lancaster',
  'Leeds',
  'Leicester',
  'Lichfield',
  'Lincoln',
  'Lisburn',
  'Liverpool',
  'Londonderry',
  'London',
  'Manchester',
  'Milton Keynes',
  'Newcastle-upon-Tyne',
  'Newport',
  'Newry',
  'Norwich',
  'Nottingham',
  'Oxford',
  'Perth',
  'Peterborough',
  'Plymouth',
  'Portsmouth',
  'Preston',
  'Ripon',
  'Salford',
  'Salisbury',
  'Sheffield',
  'Southampton',
  'Southend-on-Sea',
  'St Albans',
  'St Asaph',
  'St Davids',
  'Stirling',
  'Stoke on Trent',
  'Sunderland',
  'Swansea',
  'Truro',
  'Wakefield',
  'Wells',
  'Westminster',
  'Wolverhampton',
  'Worcester',
  'Wrexham',
  'York',
];
